apiVersion: apps/v1
kind: Deployment
metadata:
  name: authorizationdepl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Authorization
  template:
    metadata:
      labels:
        app: Authorization
    spec:
      containers:
      - name: authorization
        image: auditcr.azurecr.io/auditauthorizationrepos:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: authorizationsn

---
apiVersion: v1
kind: Service
metadata:
  name: authorization
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: Authorization